obstacle:
	g++ ObstacleAvoidance.cpp -o ObstacleAvoidance.out -I"/home/ductrung1802/GIT/ROS 2/fuzzy_logic_cpp/fuzzylite/fuzzylite" -L"/home/ductrung1802/GIT/ROS 2/fuzzy_logic_cpp/fuzzylite/fuzzylite/release/bin" -lfuzzylite-static --std=c++11

	./ObstacleAvoidance.out

	rm ./ObstacleAvoidance.out